In [1]:
import pandas as pd

In [2]:
path_birdbase =  "/home/elladarte/Documentos/my_github/avesrag-dataset-builder/data/raw/BIRDBASEv2025.1.xlsx"

In [3]:
df_birdbase = pd.read_excel(
    path_birdbase,sheet_name="Data",skiprows=1
)
df_birdbase

,IOC 15.1,English Name (BirdLife > IOC > Clements>AviList),Latin (BirdLife > IOC > Clements>AviList),HBW/BirdLife International (v9.1),IOC World Bird List (v15.1),eBird/Clements (V2024b),AviList v1 2025,Order,Family IOC 15.1,Family Clements v2024b,...,BrS1,BrS2,Prod1,Prod2,Flightlessness,Mig,Alt,Irreg,Disp,Sed
0,1,Common Ostrich,Struthio camelus,Struthio camelus,Struthio camelus,Struthio camelus,Struthio camelus,Struthioniformes,Struthionidae,Struthionidae,...,NaN,NaN,NaN,NaN,Yes,NaN,NaN,1.0,NaN,1.0
1,6,Somali Ostrich,Struthio molybdophanes,Struthio molybdophanes,Struthio molybdophanes,Struthio molybdophanes,Struthio molybdophanes,Struthioniformes,Struthionidae,Struthionidae,...,NaN,NaN,NaN,NaN,Yes,NaN,NaN,1.0,NaN,1.0
2,8,Greater Rhea,Rhea americana,Rhea americana,Rhea americana,Rhea americana,Rhea americana,Rheiformes,Rheidae,Rheidae,...,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,1.0
3,14,Lesser Rhea,Rhea pennata,Rhea pennata,Rhea pennata,Rhea pennata,Rhea pennata,Rheiformes,Rheidae,Rheidae,...,NaN,NaN,NaN,NaN,Yes,NaN,1.0,NaN,NaN,1.0
4,18,Southern Brown Kiwi,Apteryx australis,Apteryx australis,Apteryx australis,Apteryx australis,Apteryx australis,Apterygiformes,Apterygidae,Apterygidae,...,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11584,37962,White-bellied Tanager,Tangara brasiliensis,Tangara brasiliensis,Tangara brasiliensis,Tangara brasiliensis,Tangara brasiliensis,Passeriformes,Thraupidae,Thraupidae,...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,1.0
11585,37964,Paradise Tanager,Tangara chilensis,Tangara chilensis,Tangara chilensis,Tangara chilensis,Tangara chilensis,Passeriformes,Thraupidae,Thraupidae,...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN
11586,37969,Opal-crowned Tanager,Tangara callophrys,Tangara callophrys,Tangara callophrys,Tangara callophrys,Tangara callophrys,Passeriformes,Thraupidae,Thraupidae,...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN
11587,37970,Opal-rumped Tanager,Tangara velia,Tangara velia,Tangara velia,Tangara velia,Tangara velia,Passeriformes,Thraupidae,Thraupidae,...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN
11588,37974,Silver-breasted Tanager,Tangara cyanomelas,Tangara cyanomelas,NaN,NaN,NaN,Passeriformes,NaN,NaN,...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,1.0

In [4]:
df_birdbase.columns

Index(['IOC 15.1', 'English Name (BirdLife > IOC > Clements>AviList)',
       'Latin (BirdLife > IOC > Clements>AviList)',
       'HBW/BirdLife International (v9.1)', 'IOC World Bird List (v15.1)',
       'eBird/Clements (V2024b)', 'AviList v1 2025', 'Order',
       'Family IOC 15.1', 'Family Clements v2024b',
       'Family HBW/BirdLife v9.1 (2024)', 'Family AviList v1 2025', 'Genus',
       'Species', 'Source', '2024 IUCN Red List category', 'RR', 'ISL', 'RLM',
       'LAT', 'Female MinMass', 'Female MaxMass', 'Male MinMass',
       'Male MaxMass', 'Unsexed MinMass', 'Unsexed MaxMass', 'Average Mass',
       'Xmin', 'NormMin', 'Elevational Range', 'NormMax', 'Xmax', 'F', 'BM',
       'WD', 'SH', 'SV', 'G', 'PL', 'R', 'D', 'A', 'RV', 'C', 'W', 'SE', 'O',
       'O- DESC', 'Primary Habitat', 'HB', 'Primary Diet', 'IN-Wt', 'FR-Wt',
       'NE-Wt', 'SE-Wt', 'VE-Wt', 'FI-Wt', 'SC-Wt', 'PL-Wt', 'MS-Wt', 'SUM-Wt',
       'Desc', 'DB', 'Diet_Lit', 'ESI', 'Social_1', 'Social_2', 'Social_3',
       'Social_4', 'Social_5', 'Social_6', 'Mono', 'Poly', 'Coop', 'Nest_Type',
       'Nest_SBS', 'Brd1', 'Brd2', 'Clutch_Min', 'Clutch_Max', 'Incu_Sex',
       'Incu1', 'Incu2', 'Fldg1', 'Fldg2', 'Para.1', 'Para.2', 'BrS1', 'BrS2',
       'Prod1', 'Prod2', 'Flightlessness', 'Mig', 'Alt', 'Irreg', 'Disp',
       'Sed'],
      dtype='object')

In [6]:
df_birdbase_base = df_birdbase[
    [
        "eBird/Clements (V2024b)",
        "Species",
        "2024 IUCN Red List category",
        "ISL",  # Restrita a ilha
        "RLM",  # Região Globo
        "LAT",  # Distribuição Latitudinal
        "Average Mass",  # Média de peso

        # Habitats
        "F",   # Floresta
        "BM",  # Bambuzais
        "WD",  # Florestas secas e savânicas
        "SH",  # Arbustais e formações abertas com vegetação secundária
        "SV",  # Savanas e campos arborizados
        "G",   # Campos e gramíneas de altitude
        "PL",  # Planícies e áreas semiáridas abertas
        "R",   # Áreas rochosas, serras e afloramentos
        "D",   # Desertos verdadeiros
        "A",   # Ambientes artificiais e antrópicos
        "C",   # Ambientes costeiros
        "RV",  # Ambientes ripários e florestas de galeria
        "W",   # Áreas úmidas interiores
        "SE",  # Mar aberto/pelágico
        "O",   # Outros
        "Primary Habitat",  # Habitat principal

        # Dietas
        "Primary Diet",  # Dieta principal
        "IN-Wt",  # Insetívora / Invertebrívora
        "FR-Wt",  # Frugívora
        "NE-Wt",  # Nectarívora
        "SE-Wt",  # Granívora / Sementívora
        "VE-Wt",  # Carnívora (vertebrados terrestres)
        "FI-Wt",  # Piscívora
        "SC-Wt",  # Necrófaga / Oportunista
        "PL-Wt",  # Herbívora (não reprodutiva)
        "MS-Wt",  # Miscelânea / Ovivora

        # Comportamento social
        "Social_1",  # Colonial
        "Social_2",  # Social
        "Social_3",  # Pares e grupos familiares
        "Social_4",  # Individualmente e pares
        "Social_5",  # Solitário
        "Social_6",  # Lekking

        # Sistema reprodutivo
        "Mono",  # Monogâmica
        "Poly",  # Poligâmica

        "Nest_Type", # Tipo de ninho
        "Nest_SBS", # Substrato do ninho

        #  Movimento
        "Mig",    # Migratória
        "Alt",    # Migração altitudinal
        "Irreg",  # Nômade
        "Disp",   # Dispersão de longa distância
        "Sed",    # Sedentária
    ]
]

df_birdbase_base

,eBird/Clements (V2024b),Species,2024 IUCN Red List category,ISL,RLM,LAT,Average Mass,F,BM,WD,...,Social_6,Mono,Poly,Nest_Type,Nest_SBS,Mig,Alt,Irreg,Disp,Sed
0,Struthio camelus,camelus,LC,0,F,2,114500.000000,NaN,NaN,3.0,...,0,0.0,1.0,SC,G,NaN,NaN,1.0,NaN,1.0
1,Struthio molybdophanes,molybdophanes,VU,0,F,2,107875.000000,NaN,NaN,3.0,...,0,0.0,1.0,SC,G,NaN,NaN,1.0,NaN,1.0
2,Rhea americana,americana,NT,0,L,2,25250.000000,NaN,NaN,NaN,...,0,0.0,1.0,SC,G,NaN,NaN,NaN,NaN,1.0
3,Rhea pennata,pennata,LC,0,L,2,21925.000000,NaN,NaN,NaN,...,0,0.0,1.0,SC,"G,Z,S",NaN,1.0,NaN,NaN,1.0
4,Apteryx australis,australis,VU,1,Z,3,2602.500000,1.0,NaN,NaN,...,0,1.0,0.0,"BU,CV",G,NaN,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11584,Tangara brasiliensis,brasiliensis,LC,0,L,1,20.000000,1.0,NaN,NaN,...,NaN,NaN,NaN,CP,"S,T",NaN,NaN,NaN,NaN,1.0
11585,Tangara chilensis,chilensis,LC,0,L,1,19.600000,1.0,NaN,NaN,...,0,NaN,NaN,CP,T,NaN,NaN,NaN,NaN,NaN
11586,Tangara callophrys,callophrys,LC,0,L,1,23.333333,1.0,NaN,NaN,...,0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11587,Tangara velia,velia,LC,0,L,1,20.333333,1.0,NaN,NaN,...,0,NaN,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN
11588,NaN,cyanomelas,LC,0,L,1,21.000000,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0