In [1]:
import pandas as pd

In [ ]:
path_zenodo = 'data/raw/2021.07.26 CBRO 2021 Zenodo Release.xlsx'

In [3]:
df_zenodo = pd.read_excel(
    path_zenodo,sheet_name="Lista Primária"
)

In [4]:
df_especie = df_zenodo[df_zenodo["Categoria"]=="Espécie"]
df_especie.head()

,#,#CBRO,Categoria,Nome do táxon (com autoria),Nome do táxon (sem autoria),Autoria,Data,Totais,Ordem,Subordem,...,Família,Subfamília,Gênero,Espécie,Subespécie,Nome em Português,English Name,Status,Notas (português),Notes (English)
3,4,CBRO#0004,Espécie,"Rhea americana (Linnaeus, 1758)",Rhea americana,Linnaeus,1758.0,3.0,Rheiformes,NaN,...,Rheidae,NaN,Rhea,americana,NaN,ema,Greater Rhea,BR,NaN,NaN
10,11,CBRO#0011,Espécie,"Tinamus tao Temminck, 1815",Tinamus tao,Temminck,1815.0,2.0,Tinamiformes,NaN,...,Tinamidae,NaN,Tinamus,tao,NaN,azulona,Gray Tinamou,BR,NaN,NaN
13,14,CBRO#0014,Espécie,"Tinamus solitarius (Vieillot, 1819)",Tinamus solitarius,Vieillot,1819.0,0.0,Tinamiformes,NaN,...,Tinamidae,NaN,Tinamus,solitarius,NaN,macuco,Solitary Tinamou,BR,NaN,NaN
14,15,CBRO#0015,Espécie,"Tinamus major (Gmelin, 1789)",Tinamus major,Gmelin,1789.0,4.0,Tinamiformes,NaN,...,Tinamidae,NaN,Tinamus,major,NaN,inhambu-serra,Great Tinamou,BR,NaN,NaN
19,20,CBRO#0020,Espécie,"Tinamus guttatus Pelzeln, 1863",Tinamus guttatus,Pelzeln,1863.0,0.0,Tinamiformes,NaN,...,Tinamidae,NaN,Tinamus,guttatus,NaN,inhambu-galinha,White-throated Tinamou,BR,NaN,NaN

In [5]:
df_especie.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1971 entries, 3 to 4934
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   #                            1971 non-null   int64
 1   #CBRO                        1971 non-null   object
 2   Categoria                    1971 non-null   object
 3   Nome do táxon (com autoria)  1971 non-null   object
 4   Nome do táxon (sem autoria)  1971 non-null   object
 5   Autoria                      1969 non-null   object
 6   Data                         1970 non-null   float64
 7   Totais                       1971 non-null   float64
 8   Ordem                        1971 non-null   object
 9   Subordem                     1211 non-null   object
 10  Infraordem                   737 non-null    object
 11  Parvordem                    1119 non-null   object
 12  Superfamília                 499 non-null    object
 13  Família                      1971 non-null   object
 14  Subfamília                   1358 non-null   object
 15  Gênero                       1971 non-null   object
 16  Espécie                      1971 non-null   object
 17  Subespécie                   1 non-null      object
 18  Nome em Português            1971 non-null   object
 19  English Name                 1971 non-null   object
 20  Status                       1971 non-null   object
 21  Notas (português)            342 non-null    object
 22  Notes (English)              342 non-null    object
dtypes: float64(2), int64(1), object(20)
memory usage: 369.6+ KB

In [6]:
df_especie_new = df_especie[
    [
        "Nome do táxon (sem autoria)",
        "Ordem",
        "Família",
        "Gênero",
        "Espécie",
        "Nome em Português",
        "English Name",
        "Status"
    ]
]
df_especie_new

,Nome do táxon (sem autoria),Ordem,Família,Gênero,Espécie,Nome em Português,English Name,Status
3,Rhea americana,Rheiformes,Rheidae,Rhea,americana,ema,Greater Rhea,BR
10,Tinamus tao,Tinamiformes,Tinamidae,Tinamus,tao,azulona,Gray Tinamou,BR
13,Tinamus solitarius,Tinamiformes,Tinamidae,Tinamus,solitarius,macuco,Solitary Tinamou,BR
14,Tinamus major,Tinamiformes,Tinamidae,Tinamus,major,inhambu-serra,Great Tinamou,BR
19,Tinamus guttatus,Tinamiformes,Tinamidae,Tinamus,guttatus,inhambu-galinha,White-throated Tinamou,BR
...,...,...,...,...,...,...,...,...
4924,Tangara brasiliensis,Passeriformes,Thraupidae,Tangara,brasiliensis,cambada-de-chaves,White-bellied Tanager,"BR, En"
4925,Tangara chilensis,Passeriformes,Thraupidae,Tangara,chilensis,sete-cores-da-amazônia,Paradise Tanager,BR
4929,Tangara callophrys,Passeriformes,Thraupidae,Tangara,callophrys,saíra-opala,Opal-crowned Tanager,BR
4930,Tangara velia,Passeriformes,Thraupidae,Tangara,velia,saíra-diamante,Opal-rumped Tanager,BR
4934,Tangara cyanomelas,Passeriformes,Thraupidae,Tangara,cyanomelas,saíra-pérola,Silver-breasted Tanager,"BR, En"

In [7]:
df_especie_new = df_especie_new.rename(
    columns={
        "Nome do táxon (sem autoria)": "taxonomia",
        "Ordem": "ordem",
        "Família": "familia",
        "Gênero": "genero",
        "Espécie": "especie",
        "Nome em Português": "nome_pt",
        "English Name": "nome_en",
        "Status": "staus_cbro"
    },
)
df_especie_new

,taxonomia,ordem,familia,genero,especie,nome_pt,nome_en,staus_cbro
3,Rhea americana,Rheiformes,Rheidae,Rhea,americana,ema,Greater Rhea,BR
10,Tinamus tao,Tinamiformes,Tinamidae,Tinamus,tao,azulona,Gray Tinamou,BR
13,Tinamus solitarius,Tinamiformes,Tinamidae,Tinamus,solitarius,macuco,Solitary Tinamou,BR
14,Tinamus major,Tinamiformes,Tinamidae,Tinamus,major,inhambu-serra,Great Tinamou,BR
19,Tinamus guttatus,Tinamiformes,Tinamidae,Tinamus,guttatus,inhambu-galinha,White-throated Tinamou,BR
...,...,...,...,...,...,...,...,...
4924,Tangara brasiliensis,Passeriformes,Thraupidae,Tangara,brasiliensis,cambada-de-chaves,White-bellied Tanager,"BR, En"
4925,Tangara chilensis,Passeriformes,Thraupidae,Tangara,chilensis,sete-cores-da-amazônia,Paradise Tanager,BR
4929,Tangara callophrys,Passeriformes,Thraupidae,Tangara,callophrys,saíra-opala,Opal-crowned Tanager,BR
4930,Tangara velia,Passeriformes,Thraupidae,Tangara,velia,saíra-diamante,Opal-rumped Tanager,BR
4934,Tangara cyanomelas,Passeriformes,Thraupidae,Tangara,cyanomelas,saíra-pérola,Silver-breasted Tanager,"BR, En"

In [ ]:
df_especie_new.to_json(
    "data/interim/zenodo_bird_brasil.json",
    orient="records",
    force_ascii=False
)